<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Clinic;

class ClinicSeeder extends Seeder
{
    /**
     * Запуск сидера
     */
    public function run(): void
    {
        Clinic::truncate(); // Очистим таблицу перед вставкой

        $clinics = [
            [
                'name' => 'Биосфера',
                'country' => 'Россия',
                'region' => 'Краснодарский край',
                'city' => 'г.Краснодар',
                'street' => 'ул. Горького',
                'house' => 'д.217',
                'address_comment' => 'Дмитровская Дамба"',
                'logo' => 'clinics/logo/logo-biosfera.png',
                'description' => 'Полный спектр ветеринарных услуг: терапия, хирургия, вакцинация, анализы и груминг.',
                'services' => [1, 2, 3, 4],
                'doctors' => [1, 2],
                'phone1' => ' +7 (861) 251 67 85',
                'phone2' => '0',
                'email' => 'info@hvostvet.ru',
                'telegram' => '@dobrykhvost',
                'whatsapp' => '',
                'website' => 'https://biosfera.vet/',
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
            ],
            [
                'name' => 'Зоомед Центр "Лапа+"',
                'country' => 'Россия',
                'region' => 'Санкт-Петербург',
                'city' => 'Санкт-Петербург',
                'street' => 'Невский проспект',
                'house' => '105',
                'address_comment' => 'Вход со двора, 2 этаж',
                'logo' => '',
                'description' => 'Современный ветеринарный центр с лабораторией, цифровым рентгеном и отделением реабилитации животных.',
                'services' => [2, 5, 7],
                'doctors' => [3, 4, 5],
                'phone1' => '+7 (812) 555-77-88',
                'phone2' => null,
                'email' => 'contact@lapaplus.ru',
                'telegram' => '@lapaplus_vet',
                'whatsapp' => 'https://wa.me/78125557788',
                'schedule' => 'с 9:00 до 21:00',
                'workdays' => 'Пн–Сб',
            ],
            [
                'name' => 'Ветеринарная клиника "Айболит"',
                'country' => 'Россия',
                'region' => 'Свердловская область',
                'city' => 'Екатеринбург',
                'street' => 'Малышева',
                'house' => '56А',
                'address_comment' => 'Около ТЦ "Пассаж"',
                'logo' => '',
                'description' => 'Сеть клиник "Айболит" — помощь питомцам 24/7. Стационар, хирургия, УЗИ, стоматология.',
                'services' => [1, 3, 6, 8],
                'doctors' => [6, 7],
                'phone1' => '+7 (343) 333-22-11',
                'phone2' => null,
                'email' => 'aibolit24@vet.ru',
                'telegram' => '@aibolit_ekb',
                'whatsapp' => 'https://wa.me/73433332211',
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
            ],
            [
                'name' => 'Ветцентр "ЗоДоктор"',
                'country' => 'Россия',
                'region' => 'Новосибирская область',
                'city' => 'Новосибирск',
                'street' => 'Красный проспект',
                'house' => '210',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Профессиональная ветеринарная помощь для кошек и собак. Есть лаборатория и груминг-салон.',
                'services' => [1, 2, 4],
                'doctors' => [8, 9],
                'phone1' => '+7 (383) 123-45-67',
                'phone2' => null,
                'email' => 'info@zodoctor.ru',
                'telegram' => '@zodoctor',
                'whatsapp' => null,
                'schedule' => 'с 9:00 до 20:00',
                'workdays' => 'Пн–Сб',
            ],
            [
                'name' => 'Клиника "Мур-Мяу"',
                'country' => 'Россия',
                'region' => 'Калужская область',
                'city' => 'Калуга',
                'street' => 'Кирова',
                'house' => '17',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Домашняя атмосфера и профессиональные врачи. Вакцинация, чипирование, терапия и груминг.',
                'services' => [1, 2, 5],
                'doctors' => [10],
                'phone1' => '+7 (4842) 500-111',
                'phone2' => null,
                'email' => 'hello@murmyau.ru',
                'telegram' => null,
                'whatsapp' => null,
                'schedule' => 'с 10:00 до 20:00',
                'workdays' => 'Вт–Вс',
            ],
            [
                'name' => 'VetLine — Центр здоровья животных',
                'country' => 'Россия',
                'region' => 'Татарстан',
                'city' => 'Казань',
                'street' => 'Пушкина',
                'house' => '43',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Современные технологии диагностики и лечения домашних питомцев. Круглосуточный приём.',
                'services' => [3, 6, 7],
                'doctors' => [11, 12],
                'phone1' => '+7 (843) 333-99-00',
                'phone2' => '+7 (987) 654-32-10',
                'email' => 'info@vetline.ru',
                'telegram' => '@vetline_kzn',
                'whatsapp' => 'https://wa.me/79876543210',
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
            ],
            [
                'name' => 'Клиника домашних животных "ЗооМир"',
                'country' => 'Россия',
                'region' => 'Ростовская область',
                'city' => 'Ростов-на-Дону',
                'street' => 'Садовая',
                'house' => '98',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Лечение и профилактика болезней животных. Консультации по питанию и уходу.',
                'services' => [1, 4, 5],
                'doctors' => [13, 14],
                'phone1' => '+7 (863) 200-77-55',
                'phone2' => null,
                'email' => 'info@zoomir.ru',
                'telegram' => '@zoomir',
                'whatsapp' => null,
                'schedule' => 'с 8:00 до 21:00',
                'workdays' => 'Пн–Сб',
            ],
            [
                'name' => 'Центр "ДоброВет"',
                'country' => 'Россия',
                'region' => 'Пермский край',
                'city' => 'Пермь',
                'street' => 'Куйбышева',
                'house' => '150',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Хирургия, вакцинация, стоматология и лаборатория. Помощь 24/7.',
                'services' => [2, 3, 7, 9],
                'doctors' => [15, 16],
                'phone1' => '+7 (342) 400-44-55',
                'phone2' => null,
                'email' => 'contact@dobrovet.ru',
                'telegram' => null,
                'whatsapp' => null,
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
            ],
            [
                'name' => 'Здоровый Хвост',
                'country' => 'Россия',
                'region' => 'Самарская область',
                'city' => 'Самара',
                'street' => 'Московское шоссе',
                'house' => '75',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Ветеринарная помощь для кошек, собак и экзотических животных.',
                'services' => [1, 2, 3],
                'doctors' => [17],
                'phone1' => '+7 (846) 555-33-22',
                'phone2' => null,
                'email' => 'info@hvostsamara.ru',
                'telegram' => null,
                'whatsapp' => null,
                'schedule' => 'с 9:00 до 21:00',
                'workdays' => 'Пн–Сб',
            ],
            [
                'name' => 'VetCare — круглосуточная помощь',
                'country' => 'Россия',
                'region' => 'Краснодарский край',
                'city' => 'Краснодар',
                'street' => 'Северная',
                'house' => '145',
                'address_comment' => '',
                'logo' => '',
                'description' => 'Ветеринарная клиника с диагностикой, хирургией и рентгеном. Приём без записи.',
                'services' => [2, 4, 6],
                'doctors' => [18, 19],
                'phone1' => '+7 (861) 999-22-33',
                'phone2' => '+7 (918) 222-11-22',
                'email' => 'info@vetcare.ru',
                'telegram' => '@vetcare_krd',
                'whatsapp' => 'https://wa.me/79182221122',
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
            ],
            // + ещё 10 похожих записей
        ];

        // Добавим еще 10 клиник (для краткости — шаблонно)
        for ($i = 1; $i <= 10; $i++) {
            $clinics[] = [
                'name' => "Ветклиника №{$i}",
                'country' => 'Россия',
                'region' => 'Область №' . $i,
                'city' => 'Город ' . $i,
                'street' => 'Улица ' . $i,
                'house' => rand(1, 200),
                'address_comment' => '',
                'logo' => '',
                'description' => 'Типовая клиника с общим приёмом и терапией домашних животных.',
                'services' => [1, 2],
                'doctors' => [rand(1, 5)],
                'phone1' => '+7 (900) ' . rand(100, 999) . '-' . rand(10, 99) . '-' . rand(10, 99),
                'phone2' => null,
                'email' => 'clinic' . $i . '@mail.ru',
                'telegram' => null,
                'whatsapp' => null,
                'schedule' => 'с 9:00 до 20:00',
                'workdays' => 'Пн–Сб',
            ];
        }

        foreach ($clinics as $clinic) {
            Clinic::create($clinic);
        }
    }
}
