<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Clinic;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class ClinicSeeder extends Seeder
{
    /**
     * Запуск сидера
     */
    public function run(): void
    {
        // Отключаем внешние ключи, чтобы безопасно очистить таблицы
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('clinics')->truncate();
        DB::table('clinic_service')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Основные клиники
        $clinics = [
            [
                'name' => 'Биосфера',
                'country' => 'Россия',
                'region' => 'Краснодарский край',
                'city' => 'Краснодар',
                'street' => 'ул. Горького',
                'house' => 'д.217',
                'address_comment' => 'Дмитровская Дамба',
                'logo' => 'clinics/logo/logo-biosfera.png',
                'description' => '',
                'phone1' => '+7 (861) 251-67-85',
                'phone2' => null,
                'email' => 'info@hvostvet.ru',
                'telegram' => 'dobrykhvost',
                'whatsapp' => null,
                'website' => 'https://biosfera.vet/',
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
                'service_ids' => [1, 2, 3, 4],
            ],
            [
                'name' => 'Слон',
                'country' => 'Россия',
                'region' => 'Краснодарский край',
                'city' => 'Краснодар',
                'street' => 'Невский проспект',
                'house' => '105',
                'address_comment' => 'Вход со двора, 2 этаж',
                'logo' => 'clinics/logo/slon.png',
                'description' => 'Современный ветеринарный центр с лабораторией, цифровым рентгеном и отделением реабилитации животных.',
                'phone1' => '+7 (812) 555-77-88',
                'phone2' => null,
                'email' => 'contact@lapaplus.ru',
                'telegram' => 'lapaplus_vet',
                'whatsapp' => 'https://wa.me/78125557788',
                'website' => null,
                'schedule' => 'с 9:00 до 21:00',
                'workdays' => 'Пн–Сб',
                'service_ids' => [2, 5, 7],
            ],
            [
                'name' => 'ВетЛазарет',
                'country' => 'Россия',
                'region' => 'Краснодарский край',
                'city' => 'Краснодар',
                'street' => 'Малышева',
                'house' => '56А',
                'address_comment' => 'Около ТЦ "Пассаж"',
                'logo' => 'clinics/logo/vetlazaret.png',
                'description' => 'Ветлазарет — помощь питомцам 24/7. Стационар, хирургия, УЗИ, стоматология.',
                'phone1' => '+7 (343) 333-22-11',
                'phone2' => null,
                'email' => 'aibolit24@vet.ru',
                'telegram' => 'aibolit_ekb',
                'whatsapp' => 'https://wa.me/73433332211',
                'website' => null,
                'schedule' => 'круглосуточно',
                'workdays' => 'Пн–Вс',
                'service_ids' => [1, 3, 6, 8],
            ],
    [
        'name' => 'Счастливая Морда',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'ул. Героев Разведчиков',
        'house' => '26/4',
        'address_comment' => 'Цокольный этаж жилого дома, отдельный вход',
        'logo' => 'clinics/logo/chactlivay_morda.png',
        'description' => 'Круглосуточная ветеринарная помощь, УЗИ, хирургия, стационар, вакцинация и выезд на дом.',
        'phone1' => '+7 (905) 476-75-75',
        'phone2' => '+7 (918) 400-00-00',
        'email' => 'info@doktorvet-krd.ru',
        'telegram' => '8 (905) 476-75-75',
        'whatsapp' => 'https://wa.me/8 (905) 476-75-75',
        'website' => 'https://vetclinic23.ru/',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс',
        'service_ids' => [1, 2, 3, 4, 5, 6, 7, 8],
    ],
    [
        'name' => 'Семейная ветеринарная клиника ЗооЛайн',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Васнецова',
        'house' => '56',
        'address_comment' => 'Рядом с парком, отдельное здание',
        'logo' => '',
        'description' => 'Полный спектр услуг: терапия, дерматология, стоматология, лабораторная диагностика и груминг.',
        'phone1' => '+7 (861) 274-44-44',
        'phone2' => null,
        'email' => 'zooline-krd@yandex.ru',
        'telegram' => 'zooline_krd',
        'whatsapp' => 'https://wa.me/78612744444',
        'website' => 'https://zooline-krd.ru',
        'schedule' => 'с 9:00 до 20:00',
        'workdays' => 'Пн–Сб',
        'service_ids' => [1, 2, 5, 6, 7, 9],
    ],
    [
        'name' => 'Ветеринарная клиника Био-Вет',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Уральская',
        'house' => '107/2',
        'address_comment' => 'Вход с торца, рядом с аптекой',
        'logo' => '',
        'description' => 'Специализированная диагностика, УЗИ, ЭКГ, анализы, вакцинация и профилактика паразитов.',
        'phone1' => '+7 (861) 292-22-92',
        'phone2' => '+7 (918) 292-22-92',
        'email' => 'biovetkrd@mail.ru',
        'telegram' => 'biovet_krd',
        'whatsapp' => 'https://wa.me/79182922292',
        'website' => 'https://biovet-krd.ru',
        'schedule' => 'с 8:00 до 20:00',
        'workdays' => 'Пн–Вс',
        'service_ids' => [1, 2, 5, 6, 8],
    ],
    [
        'name' => 'Клиника для животных ЗооМир',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Героя Аверкиева',
        'house' => '15',
        'address_comment' => 'На первом этаже ТЦ "ЗооМир"',
        'logo' => '',
        'description' => 'Современное оборудование, опытные врачи, отделение неотложной помощи и косметология для животных.',
        'phone1' => '+7 (861) 237-77-77',
        'phone2' => null,
        'email' => 'zoomir-krd@info.ru',
        'telegram' => 'zoomir_krd',
        'whatsapp' => 'https://wa.me/78612377777',
        'website' => 'https://zoomir-krd.ru',
        'schedule' => 'с 9:00 до 21:00',
        'workdays' => 'Пн–Сб',
        'service_ids' => [1, 2, 3, 4, 5, 7],
    ],
    [
        'name' => 'Ветеринарная клиника Айболит',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Красная',
        'house' => '147',
        'address_comment' => 'Центр города, рядом с универмагом',
        'logo' => '',
        'description' => 'Одна из старейших клиник Краснодара. Приём всех видов животных, включая экзотических.',
        'phone1' => '+7 (861) 262-22-22',
        'phone2' => '+7 (918) 262-22-22',
        'email' => 'aibolit-krd@yandex.ru',
        'telegram' => 'aibolit_krd',
        'whatsapp' => 'https://wa.me/79182622222',
        'website' => 'https://aibolit-krd.ru',
        'schedule' => 'с 8:30 до 20:00',
        'workdays' => 'Пн–Вс',
        'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Центр Ветеринарной Медицины',
        'country' => 'Россия',
        'region' => 'Донецкая Народная республика',
        'city' => 'Донецк',
        'street' => 'пр-т Мира',
        'house' => '8',
        'address_comment' => '',
        'logo' => 'clinics/logo/dnr/cvm_dnr.png',
        'description' => 'Работает по предварительной записи',
        'phone1' => '+7 (949) 305-81-87',
        'phone2' => '+7(856) 345-03-15',
        'email' => 'cvm.dn@mail.ru',
        'telegram' => '',
        'whatsapp' => '',
        'website' => 'https://cvm-donetsk.ru/',
        'schedule' => 'с 8:00 до 16:00',
        'workdays' => 'Пн–Вс',
        'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Динго Зооветеринарной центр',
        'country' => 'Россия',
        'region' => 'Донецкая Народная республика',
        'city' => 'Донецк',
        'street' => 'ул.50-летия СССР',
        'house' => '140',
        'address_comment' => '',
        'logo' => 'clinics/logo/dnr/dingo_dnr.png',
        'description' => 'Клиника в городе Донецк',
        'phone1' => '+7 (949) 333-25-83 ',
        'phone2' => '+7(856) 335-41-90',
        'email' => 'donvet@mail.ru',
        'telegram' => '',
        'whatsapp' => '',
        'website' => 'http://dingo-vet.com/index.php?id=17991&show=89399',
        'schedule' => 'с 9:00 до 17:00',
        'workdays' => 'Пн–Вс',
        'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
        [
        'name' => 'Доверие',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Первомайская',
        'house' => '43',
        'address_comment' => 'Есть филиалы, работает круглосуточно',
        'logo' => null,
        'description' => 'Ветеринарная клиника. Диагностика: УЗИ, рентген, лабораторные исследования.',
        'phone1' => '+7 (861) 275-39-28',
        'phone2' => '+7 918 090-02-51',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'doverie-23.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Участковая ветеринарная лечебница Центральная',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'имени Калинина',
        'house' => '15/1',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Государственная ветеринарная лечебница.',
        'phone1' => '+7 (861) 213-06-53',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'krasnodarvet.ru',
        'schedule' => 'Пн–Вс: 08:00–20:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Ле Мурр',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Пашковская',
        'house' => '52',
        'address_comment' => 'Имеется ветеринарная аптека',
        'logo' => null,
        'description' => 'Ветеринарная клиника с аптекой.',
        'phone1' => '+7 (908) 677-87-27',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetaptekakrasnodar.ru',
        'schedule' => 'Пн–Вс: 09:00–19:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Слон',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Достоевского',
        'house' => '105',
        'address_comment' => 'Имеется лаборатория',
        'logo' => null,
        'description' => 'Ветеринарная клиника с лабораторией.',
        'phone1' => '+7 (861) 234-56-78',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => null,
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Участковая ветеринарная лечебница Калининская',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => '1 Мая',
        'house' => null,
        'address_comment' => null,
        'logo' => null,
        'description' => 'Государственная ветеринарная лечебница.',
        'phone1' => null,
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => null,
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Ника',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Ставропольская',
        'house' => '107/10',
        'address_comment' => 'Скидки на вакцинацию, стерилизацию и кастрацию',
        'logo' => null,
        'description' => 'Ветеринарная клиника со скидками на базовые услуги.',
        'phone1' => '+7 (861) 234-55-55',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => null,
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Слон',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Монтажников',
        'house' => '5',
        'address_comment' => 'Имеется лаборатория',
        'logo' => null,
        'description' => 'Ветеринарная клиника с лабораторией.',
        'phone1' => '+7 (861) 234-56-78',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => null,
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Питомник',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Корницкого',
        'house' => '62',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Ветеринарная клиника с аптекой.',
        'phone1' => '+7 (861) 274-20-20',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Слон',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Казбекская',
        'house' => '18',
        'address_comment' => 'Микрорайон Солнечный, имеется лаборатория',
        'logo' => null,
        'description' => 'Ветеринарный центр с лабораторией, современные технологии.',
        'phone1' => '+7 (861) 234-56-78',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => null,
        'workdays' => null
    ],
    [
        'name' => 'Вита',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Симферопольская',
        'house' => '34А',
        'address_comment' => 'Есть стационар, возможен вызов врача на дом',
        'logo' => null,
        'description' => 'Ветеринарная клиника. Диагностика, сложные операции, стационар.',
        'phone1' => '+7 (861) 215-15-15',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Весниной Зинаиды Юрьевны',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Душистая',
        'house' => '50',
        'address_comment' => 'пос. Берёзовый',
        'logo' => null,
        'description' => 'Ветеринарная клиника. Консультации, обследования, экстренная помощь.',
        'phone1' => '+7 (861) 216-16-16',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Айболит',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'проезд 2‑й им. Стасова',
        'house' => '113/1',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Ветеринарная клиника с базовым набором услуг.',
        'phone1' => '+7 (861) 217-17-17',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'Заботавет',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Кубанская',
        'house' => '47',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Клиника ветеринарной медицины и репродукции.',
        'phone1' => '+7 (861) 218-18-18',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс',
'service_ids' => [1, 2, 5, 6, 7, 9, 10],
    ],
    [
        'name' => 'ВетПомощь24',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Северная',
        'house' => '456',
        'address_comment' => 'Круглосуточный приём, выезд врача на дом',
        'logo' => null,
        'description' => 'Ветеринарная клиника экстренной помощи. УЗИ, рентген, стационар, хирургия.',
        'phone1' => '+7 (861) 220-00-20',
        'phone2' => null,
        'email' => 'vetpomosh24@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 456-00-20',
        'website' => 'vetpomosh24.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ЗооДоктор',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Красных Партизан',
        'house' => '2/1',
        'address_comment' => 'Есть лаборатория и аптека',
        'logo' => null,
        'description' => 'Полный спектр ветеринарных услуг: терапия, хирургия, диагностика, вакцинация.',
        'phone1' => '+7 (861) 221-11-11',
        'phone2' => null,
        'email' => 'zoodoctor@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zoodoctor-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Феникс',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Московская',
        'house' => '123',
        'address_comment' => 'Специализируется на хирургии и травматологии',
        'logo' => null,
        'description' => 'Клиника с узкопрофильными специалистами: хирурги, травматологи, реабилитологи.',
        'phone1' => '+7 (861) 222-22-22',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Мурзик',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Садовая',
        'house' => '178',
        'address_comment' => 'Фокус на лечении кошек и мелких грызунов',
        'logo' => null,
        'description' => 'Ветеринарная клиника для кошек и грызунов: терапия, стоматология, УЗИ.',
        'phone1' => '+7 (861) 223-33-33',
        'phone2' => null,
        'email' => 'murzikvet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '10:00–18:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Пёс и Кот',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Российская',
        'house' => '245',
        'address_comment' => 'Семейный ветеринарный центр',
        'logo' => null,
        'description' => 'Комплексное обслуживание: терапия, вакцинация, груминг, зоомагазин.',
        'phone1' => '+7 (861) 224-44-44',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'pesikot-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВитаВет',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Тургеневское шоссе',
        'house' => '27',
        'address_comment' => 'Современный центр с цифровой диагностикой',
        'logo' => null,
        'description' => 'Клиника с цифровым рентгеном, УЗИ, эндоскопией, стационаром.',
        'phone1' => '+7 (861) 225-55-55',
        'phone2' => null,
        'email' => 'vitavet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vitavet-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Добрый Друг',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Володарского',
        'house' => '5',
        'address_comment' => 'Работает с экзотическими животными',
        'logo' => null,
        'description' => 'Лечение птиц, рептилий, грызунов. Терапия, хирургия, консультации.',
        'phone1' => '+7 (861) 226-66-66',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '10:00–18:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Скорая ВетПомощь',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'ул. им. 40-летия Победы',
        'house' => '189',
        'address_comment' => 'Экстренные вызовы 24/7, реанимация',
        'logo' => null,
        'description' => 'Служба экстренной ветеринарной помощи. Реанимация, вызов врача на дом.',
        'phone1' => '+7 (861) 227-77-77',
        'phone2' => '+7 918 555-77-77',
        'email' => 'skorvet@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 555-77-77',
        'website' => 'skorvet-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Центр Ветеринарной Кардиологии',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'ул. им. Шевченко',
        'house' => '87',
        'address_comment' => 'Специализация: болезни сердца и сосудов',
        'logo' => null,
        'description' => 'Диагностика и лечение кардиологических заболеваний у животных.',
        'phone1' => '+7 (861) 228-88-88',
        'phone2' => null,
        'email' => 'cardiovet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'cardiovet-krd.ru',
        'schedule' => '09:00–18:00',
        'workdays' => 'Пн–Пт'
    ],
        [
        'name' => 'ЗооКлиника на Красной',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Красная',
        'house' => '176',
        'address_comment' => 'В центре города, рядом с парком Горького',
        'logo' => null,
        'description' => 'Многопрофильная ветеринарная клиника. Терапия, хирургия, стоматология, УЗИ.',
        'phone1' => '+7 (861) 229-99-99',
        'phone2' => null,
        'email' => 'zooclinic-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 666-99-99',
        'website' => 'zooclinic-krasnodar.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВетЭксперт',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Дзержинского',
        'house' => '100',
        'address_comment' => 'Клиника экспертного уровня диагностики',
        'logo' => null,
        'description' => 'Высокоточная диагностика: МРТ, КТ, эндоскопия. Консультации узкопрофильных специалистов.',
        'phone1' => '+7 (861) 230-00-00',
        'phone2' => null,
        'email' => 'vetexpert-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetexpert-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Кот и Пёс',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Шевченко',
        'house' => '154',
        'address_comment' => 'Уютная клиника с дружелюбным персоналом',
        'logo' => null,
        'description' => 'Базовые ветеринарные услуги: вакцинация, чипирование, терапия, хирургия.',
        'phone1' => '+7 (861) 231-11-11',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '10:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветеринарный центр "Альянс"',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'ул. им. Володарского',
        'house' => '38',
        'address_comment' => 'Современный центр с цифровой аппаратурой',
        'logo' => null,
        'description' => 'Полный цикл ветеринарной помощи: диагностика, лечение, реабилитация.',
        'phone1' => '+7 (861) 232-22-22',
        'phone2' => null,
        'email' => 'alliancevet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'alliance-vet-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Здоровый питомец',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Офицерская',
        'house' => '45',
        'address_comment' => 'Специализируется на профилактике заболеваний',
        'logo' => null,
        'description' => 'Вакцинация, диспансеризация, консультации по кормлению и содержанию.',
        'phone1' => '+7 (861) 233-33-33',
        'phone2' => null,
        'email' => 'zdorovpit@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–18:00',
        'workdays' => 'Пн–Пт'
    ],
    [
        'name' => 'ВетСервис',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Гагарина',
        'house' => '120',
        'address_comment' => 'Выезд врача на дом, круглосуточная поддержка',
        'logo' => null,
        'description' => 'Вызов ветеринара на дом, экстренная помощь, стационар.',
        'phone1' => '+7 (861) 234-44-44',
        'phone2' => '+7 918 777-44-44',
        'email' => 'vetservice-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 777-44-44',
        'website' => 'vetservice-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Фауна',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Толстого',
        'house' => '56',
        'address_comment' => 'Клиника с акцентом на реабилитацию',
        'logo' => null,
        'description' => 'Реабилитация после травм и операций, физиотерапия, массаж.',
        'phone1' => '+7 (861) 235-55-55',
        'phone2' => null,
        'email' => 'fauna-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
   [
        'name' => 'Верный Друг',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Буденного',
        'house' => '210',
        'address_comment' => 'Работаем с 2005 года, проверенные методики',
        'logo' => null,
        'description' => 'Комплексное обслуживание животных: терапия, хирургия, вакцинация.',
        'phone1' => '+7 (861) 236-66-66',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vernyidrug-vet.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ЗооПрофи',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Карякина',
        'house' => '78',
        'address_comment' => 'Профессиональное оборудование',
        'logo' => null,
        'description' => 'Диагностика: УЗИ, рентген, лабораторные анализы. Терапия и хирургия.',
        'phone1' => '+7 (861) 237-77-77',
        'phone2' => null,
        'email' => 'zoprofi-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zoprofi-vet.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
        [
        'name' => 'Счастливый Зверь',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Шевченко',
        'house' => '92',
        'address_comment' => 'Современная клиника с дневным стационаром',
        'logo' => null,
        'description' => 'Полный спектр ветеринарных услуг: диагностика, терапия, хирургия, реабилитация. Есть дневной стационар.',
        'phone1' => '+7 (861) 238-88-88',
        'phone2' => null,
        'email' => 'happybeast-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 888-88-88',
        'website' => 'happybeast-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВетГармония',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Толстого',
        'house' => '112',
        'address_comment' => 'Акцент на гуманное лечение и комфорт животных',
        'logo' => null,
        'description' => 'Терапия, хирургия, стоматология. Используем щадящие методики и современное оборудование.',
        'phone1' => '+7 (861) 239-99-99',
        'phone2' => null,
        'email' => 'vetharmony@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetharmony-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'ЗооДоктор Плюс',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Офицерская',
        'house' => '77',
        'address_comment' => 'Есть собственная лаборатория и аптека',
        'logo' => null,
        'description' => 'Диагностика: УЗИ, рентген, анализы. Терапия, хирургия, вакцинация, чипирование.',
        'phone1' => '+7 (861) 240-00-00',
        'phone2' => null,
        'email' => 'zoodoctorplus@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zoodoctorplus-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Пушистый Друг',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Гагарина',
        'house' => '88',
        'address_comment' => 'Специализируется на лечении мелких пород собак',
        'logo' => null,
        'description' => 'Терапия, профилактика, хирургия для мелких и декоративных пород. Консультации по уходу.',
        'phone1' => '+7 (861) 241-11-11',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '10:00–18:00',
        'workdays' => 'Пн–Пт'
    ],
    [
        'name' => 'Ветеринарный центр "Оптима"',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Дзержинского',
        'house' => '155',
        'address_comment' => 'Современные методы диагностики и лечения',
        'logo' => null,
        'description' => 'УЗИ, рентген, эндоскопия, лабораторные исследования. Терапия, хирургия, стационар.',
        'phone1' => '+7 (861) 242-22-22',
        'phone2' => null,
        'email' => 'optivet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'optivet-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Добрый Ветеринар',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Северная',
        'house' => '333',
        'address_comment' => 'Круглосуточный приём, выезд на дом',
        'logo' => null,
        'description' => 'Экстренная помощь, стационар, диагностика, терапия. Возможен вызов врача на дом.',
        'phone1' => '+7 (861) 243-33-33',
        'phone2' => '+7 918 999-33-33',
        'email' => 'dobryvet@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 999-33-33',
        'website' => 'dobryvet-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВетКомфорт',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Буденного',
        'house' => '188',
        'address_comment' => 'Уютная атмосфера, индивидуальный подход',
        'logo' => null,
        'description' => 'Базовые и специализированные ветеринарные услуги. Акцент на комфорт питомца и хозяина.',
        'phone1' => '+7 (861) 244-44-44',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetkomfort-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'ЗооПомощь',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Карякина',
        'house' => '101',
        'address_comment' => 'Работаем с экзотическими животными',
        'logo' => null,
        'description' => 'Лечение птиц, рептилий, грызунов. Терапия, диагностика, консультации по содержанию.',
        'phone1' => '+7 (861) 245-55-55',
        'phone2' => null,
        'email' => 'zoopomosh@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => null,
        'schedule' => '10:00–18:00',
        'workdays' => 'Пн–Пт'
    ],
    [
        'name' => 'Ветеринарная клиника "Профи"',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Володарского',
        'house' => '66',
        'address_comment' => 'Профессиональное оборудование экспертного класса',
        'logo' => null,
        'description' => 'МРТ, КТ, УЗИ, рентген. Узкопрофильные специалисты: кардиологи, хирурги, онкологи.',
        'phone1' => '+7 (861) 246-66-66',
        'phone2' => null,
        'email' => 'profivet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'profivet-krd.ru',
        'schedule' => '09:00–19:00'
    ],
    [
        'name' => 'Ветклиника на Бабушкина',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Бабушкина',
        'house' => '160',
        'address_comment' => 'Основная клиника, круглосуточный режим работы',
        'logo' => null,
        'description' => 'Полный спектр ветеринарных услуг: хирургия, терапия, диагностика (УЗИ, рентген), стационар, вакцинация, чипирование. Работают узкопрофильные специалисты.',
        'phone1' => '+7 (861) 217-62-93',
        'phone2' => '+7 (861) 217-65-47',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetklinika-na-babushkina.ru',
        'schedule' => '08:00–22:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветеринарная клиника доктора Петросяна',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Кубанская Набережная',
        'house' => '37/12',
        'address_comment' => 'Микрорайон Центральный, 1‑й этаж',
        'logo' => null,
        'description' => 'Комплексная диагностика (УЗИ, рентген), хирургия, терапия, ветеринарная лаборатория. Приём ведут опытные специалисты.',
        'phone1' => '+7 (861) 222-33-33',
        'phone2' => null,
        'email' => 'petrosyan-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'petrosyan-vet-clinic.ru',
        'schedule' => '09:00–21:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Белая лапа',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Костылева',
        'house' => '148',
        'address_comment' => 'Микрорайон Центральный, ветеринарная лаборатория',
        'logo' => null,
        'description' => 'Диагностика (УЗИ, лабораторные анализы), терапия, хирургия, стоматология. Есть ветеринарная аптека.',
        'phone1' => '+7 (861) 244-55-55',
        'phone2' => null,
        'email' => 'belayalapa-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'belayalapa-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Борзая Краснодог',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Куйбышева',
        'house' => '2',
        'address_comment' => 'Школьный микрорайон, зоосалон и зоопарикмахерская',
        'logo' => null,
        'description' => 'Ветеринарные услуги, груминг, стрижка, уход за животными. Терапия, вакцинация, обработка от паразитов.',
        'phone1' => '+7 (861) 255-55-55',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'borzayakrasnodog.ru',
        'schedule' => '10:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Зооленд',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Оренбургская',
        'house' => '1/1',
        'address_comment' => 'Есть лаборатория, эндоскопические операции',
        'logo' => null,
        'description' => 'Эндоскопические операции, УЗИ, рентген, лабораторные исследования. Терапия, хирургия, вакцинация.',
        'phone1' => '+7 (861) 201-01-01',
        'phone2' => null,
        'email' => 'zoolend-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zoolend-vet.ru',
        'schedule' => '09:00–22:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Спасатель',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Н. С. Котлярова',
        'house' => '1',
        'address_comment' => 'Микрорайон Московский, ветеринарная лаборатория',
        'logo' => null,
        'description' => 'Терапия, хирургия, диагностика (УЗИ, рентген). Работают опытные ветеринары, есть лаборатория.',
        'phone1' => '+7 (861) 203-03-03',
        'phone2' => null,
        'email' => 'spasatel-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'spasatel-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Добрый Доктор',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Стасова',
        'house' => '134/1',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Терапия, хирургия, вакцинация. Специалисты экспертного уровня, современное оборудование.',
        'phone1' => '+7 (861) 204-04-04',
        'phone2' => null,
        'email' => 'dobrydoctor-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'dobrydoctor-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВикВет',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Репина',
        'house' => '2Д',
        'address_comment' => 'Вход слева от двери «Магнита», цокольный этаж',
        'logo' => null,
        'description' => 'Терапия, диагностика (УЗИ, рентген), вакцинация, обработка ран, хирургические операции. Есть аптека.',
        'phone1' => '+7 (861) 266-66-66',
        'phone2' => null,
        'email' => 'vikvet-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vikvet-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ирбис',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Интернациональный бульвар',
        'house' => '110',
        'address_comment' => 'Круглосуточный приём, ветеринарная аптека',
        'logo' => null,
        'description' => 'Экстренная помощь, стационар, УЗИ, рентген, терапия, хирургия. Работают круглосуточно.',
        'phone1' => '+7 (861) 212-12-12',
        'phone2' => null,
        'email' => 'irbis-vet@mail.ru',
                'telegram' => null,
        'whatsapp' => null,
        'website' => 'vikvet-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Большая Медведица',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Маяковского',
        'house' => '150',
        'address_comment' => 'Основная площадка клиники',
        'logo' => null,
        'description' => 'Многопрофильная ветеринарная клиника: хирургия, терапия, офтальмология, кардиология, онкология, стоматология. Есть круглосуточный стационар, лаборатория, эндоскопия, ингаляционный наркоз.',
        'phone1' => '+7 (861) 212-05-04',
        'phone2' => '+7 928 881-57-00',
        'email' => 'welcome@vet-kuban.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'bmedvedica-vet.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Большая Медведица (филиал)',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Кёльнская',
        'house' => '17',
        'address_comment' => 'Филиал клиники',
        'logo' => null,
        'description' => 'Полный спектр ветеринарных услуг: диагностика, терапия, хирургия, стоматология, вакцинация. Работает лаборатория.',
        'phone1' => '+7 928 881-57-00',
        'phone2' => null,
        'email' => 'welcome@vet-kuban.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'bmedvedica-vet.ru',
        'schedule' => '09:00–21:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветуправление города Краснодара (Карасунская)',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Карасунская',
        'house' => '110',
        'address_comment' => 'Государственное учреждение, КВО',
        'logo' => null,
        'description' => 'Государственные ветеринарные услуги: вакцинация, кастрация/стерилизация, УЗИ, анализы, оформление документов. Доступные цены.',
        'phone1' => '+7 (861) 202-96-56',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetupravlenie-krd.ru',
        'schedule' => '08:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветуправление города Краснодара (1 Мая)',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => '1 Мая',
        'house' => '319',
        'address_comment' => 'Государственное учреждение',
        'logo' => null,
        'description' => 'Вакцинация, кастрация, УЗИ, лабораторные исследования, оформление ветеринарных документов. Государственная клиника.',
        'phone1' => '+7 (861) 202-96-56',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetupravlenie-krd.ru',
        'schedule' => '08:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветуправление города Краснодара (Московская)',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Московская',
        'house' => '144',
        'address_comment' => 'Государственное учреждение',
        'logo' => null,
        'description' => 'Комплексная ветеринарная помощь: диагностика, терапия, хирургия, вакцинация. Государственные расценки.',
        'phone1' => '+7 (861) 202-96-56',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetupravlenie-krd.ru',
        'schedule' => '08:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Ветуправление города Краснодара (Калинина)',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Калинина',
        'house' => '15/1',
        'address_comment' => 'Государственное учреждение',
        'logo' => null,
        'description' => 'Ветеринарные услуги по госрасценкам: анализы, УЗИ, вакцинация, стерилизация, оформление документов.',
        'phone1' => '+7 (861) 202-96-56',
        'phone2' => null,
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetupravlenie-krd.ru',
        'schedule' => '08:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ЗооДоктор на Северной',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Северная',
        'house' => '222',
        'address_comment' => 'Рядом с ТЦ «Северный»',
        'logo' => null,
        'description' => 'Терапия, хирургия, УЗИ, рентген, вакцинация, чипирование. Есть аптека и лаборатория.',
        'phone1' => '+7 (861) 277-77-77',
        'phone2' => null,
        'email' => 'zoodoctor-north@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zoodoctor-north-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'ВетПомощь Плюс',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Седина',
        'house' => '189',
        'address_comment' => 'Микрорайон Центральный',
        'logo' => null,
        'description' => 'Экстренная помощь, стационар, УЗИ, рентген, терапия, хирургия. Круглосуточный приём.',
        'phone1' => '+7 (861) 288-88-88',
        'phone2' => '+7 918 111-88-88',
        'email' => 'vetpomoshplus@mail.ru',
        'telegram' => null,
        'whatsapp' => '+7 918 111-88-88',
        'website' => 'vetpomoshplus-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Лапки-Царапки',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Садовая',
        'house' => '205',
        'address_comment' => 'Специализируется на мелких животных и грызунах',
        'logo' => null,
        'description' => 'Лечение кошек, собак мелких пород, грызунов, птиц. Терапия, хирургия, вакцинация, консультации по уходу.',
        'phone1' => '+7 (861) 299-99-99',
        'phone2' => null,
        'email' => 'lapki-tsarapki@mail.ru',
                'telegram' => null,
        'whatsapp' => '+7 918 111-88-88',
        'website' => 'vetpomoshplus-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Лапа Помощи',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Архитектора Ишунина',
        'house' => '7/1 к2',
        'address_comment' => 'Микрорайон Юбилейный',
        'logo' => null,
        'description' => 'Комплексная ветеринарная помощь: терапия, хирургия, диагностика (УЗИ, рентген), стационар. Ответственный подход к лечению.',
        'phone1' => '+7 (861) 277-00-00',
        'phone2' => null,
        'email' => 'lapapomoshi-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'lapapomoshi-vet.ru',
        'schedule' => '09:00–21:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Воля',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Целиноградская',
        'house' => '68',
        'address_comment' => 'пос. Берёзовый, городской округ Краснодар',
        'logo' => null,
        'description' => 'Круглосуточная ветеринарная помощь: хирургия, терапия, диагностика (УЗИ, рентген), собственная лаборатория, стационар.',
        'phone1' => '+7 (861) 288-00-00',
        'phone2' => null,
        'email' => 'vola-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vola-krd.ru',
        'schedule' => 'круглосуточно',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Здоровье',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Тихая 9‑я',
        'house' => '11',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Ортопедические операции любой сложности, УЗИ, рентген, стационар. Приём ведут опытные специалисты.',
        'phone1' => '+7 (861) 299-00-00',
        'phone2' => null,
        'email' => 'zdorovie-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'zdorovie-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Друг',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. В. Н. Мачуги',
        'house' => '20',
        'address_comment' => 'Есть круглосуточный стационар',
        'logo' => null,
        'description' => 'Терапия, хирургия, вакцинация, обработка от паразитов. Работают узкопрофильные специалисты.',
        'phone1' => '+7 (861) 255-00-00',
        'phone2' => null,
        'email' => 'drug-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'drug-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'VetAsist',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'Геодезическая',
        'house' => '3/1',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Хирургия, терапия, УЗИ, рентген. Собственная лаборатория. Консультации по уходу и содержанию животных.',
        'phone1' => '+7 (861) 266-00-00',
        'phone2' => null,
        'email' => 'vetasist-krd@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'vetasist-vet.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Сб'
    ],
    [
        'name' => 'Слон',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'проспект Чекистов',
        'house' => '31/2',
        'address_comment' => 'Основная клиника сети',
        'logo' => null,
        'description' => 'Современные технологии в ветеринарии: хирургия, терапия, диагностика (УЗИ, МРТ, рентген), стационар, ветеринарная аптека.',
        'phone1' => '+7 (861) 244-00-00',
        'phone2' => null,
        'email' => 'slon-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'slon-krd.ru',
        'schedule' => '09:00–20:00',
        'workdays' => 'Пн–Вс'
    ],
    [
        'name' => 'Дар',
        'country' => 'Россия',
        'region' => 'Краснодарский край',
        'city' => 'Краснодар',
        'street' => 'им. Калинина',
        'house' => '316/1',
        'address_comment' => null,
        'logo' => null,
        'description' => 'Терапия, вакцинация, кастрация/стерилизация, диагностика (УЗИ, анализы). Миссия — дарить счастье питомцу и хозяину.',
        'phone1' => '+7 (861) 222-00-00',
        'phone2' => null,
        'email' => 'dar-vet@mail.ru',
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'dar-krd.ru',
        'schedule' => '09:00–19:00',
        'workdays' => 'Пн–Вс'
    ],
];

// Создаём клиники и прикрепляем услуги
foreach ($clinics as $data) {
    // Явно задаём service_ids = [1] для каждой клиники
    $serviceIds = [1];
    
    unset($data['service_ids']); // Удаляем исходный ключ, если он есть

    // ✅ Генерация slug
    $data['slug'] = Str::slug(
        $data['name'] . ' ' . $data['city'] . ' ' . $data['street']
    );

    $clinic = Clinic::create($data);
    $clinic->services()->sync($serviceIds);
}
    }
}