<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NDoctorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = [
            [
                'name' => 'Корниенко Вячеслав Геннадьевич',
                'is_verified' => 1,
                'slug' => 'kornienko-vyacheslav-gennadevich-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный травматолог, ветеринарный хирург',
                'clinic_id' => 492,
                'practice_started_at' => '2004-09-01',
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Окончил Московский Военно-Ветеринарный институт в 2002 году. Специализируется на травматологии и хирургии.',
            ],
            [
                'name' => 'Цыбанева Ирина Григорьевна',
                'is_verified' => 1,
                'slug' => 'cybaneva-irina-grigorevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач УЗИ, ветеринарный врач-терапевт, ветеринарный хирург',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Врач общей практики, специалист ультразвуковой диагностики, терапевт и хирург.',
            ],
            [
                'name' => 'Грачева Елена Николаевна',
                'is_verified' => 1,
                'slug' => 'gracheva-elena-nikolaevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-дерматолог, ветеринарный врач-терапевт',
                'clinic_id' => 492,
                'practice_started_at' => '2006-09-01',
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Окончила МГАВМ им. К.И. Скрябина в 2006 году. Работает в ветеринарии с 2004 года. Постоянный участник конференций NVC.',
            ],
            [
                'name' => 'Сизикова Наталья Константиновна',
                'is_verified' => 1,
                'slug' => 'sizikova-natalya-konstantinovna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач УЗИ, ветеринарный врач-кардиолог, ветеринарный нефролог-уролог',
                'clinic_id' => 492,
                'practice_started_at' => '2012-09-01',
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Окончила РУДН в 2010 году. Прошла повышение квалификации по кардиологии, УЗИ, болезням ЖКТ и лабораторной диагностике.',
            ],
            [
                'name' => 'Попова Алина Алексеевна',
                'is_verified' => 1,
                'slug' => 'popova-alina-alekseevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-терапевт, ветеринарный нефролог-уролог',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Специализируется на терапии и заболеваниях мочевыделительной системы (нефрология и урология).',
            ],
            [
                'name' => 'Попов Семен Сергеевич',
                'is_verified' => 1,
                'slug' => 'popov-semen-sergeevich-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-терапевт, ветеринарный стоматолог, ветеринарный травматолог, ветеринарный хирург',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Специалист широкого профиля, практикует в области хирургии, травматологии, терапевтического лечения и стоматологии.',
            ],
            [
                'name' => 'Ларионов Сергей Александрович',
                'is_verified' => 1,
                'slug' => 'larionov-sergey-aleksandrovich-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-офтальмолог, ветеринарный врач-терапевт, ветеринарный хирург',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Ведёт общий терапевтический приём, проводит офтальмологические исследования и хирургические операции.',
            ],
            [
                'name' => 'Усманов Руслан Сергеевич',
                'is_verified' => 1,
                'slug' => 'usmanov-ruslan-sergeevich-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный анестезиолог-реаниматолог',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => true,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Специализируется на анестезиологическом сопровождении операций и интенсивной терапии, в том числе для экзотических животных.',
            ],
            [
                'name' => 'Мерзлякова Ирина Васильевна',
                'is_verified' => 1,
                'slug' => 'merzlyakova-irina-vasilevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный анестезиолог-реаниматолог',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => true,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Врач анестезиолог-реаниматолог. Занимается подбором наркоза, мониторингом состояния пациентов во время операций и реанимацией.',
            ],
            [
                'name' => 'Крюкова Екатерина Евгеньевна',
                'is_verified' => 1,
                'slug' => 'kryukova-ekaterina-evgenevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный анестезиолог-реаниматолог',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => true,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Специалист по анестезии и реанимации домашних и экзотических животных.',
            ],
            [
                'name' => 'Холод Евгения Андреевна',
                'is_verified' => 1,
                'slug' => 'holod-evgeniya-andreevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-терапевт',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Ведёт общий амбулаторный и терапевтический приём, занимается первичной диагностикой заболеваний.',
            ],
            [
                'name' => 'Чеботарь Мария Николаевна',
                'is_verified' => 1,
                'slug' => 'chebotar-mariya-nikolaevna-max-vet',
                'date_of_birth' => null,
                'city_id' => 31,
                'specialization' => 'Ветеринарный врач-терапевт',
                'clinic_id' => 492,
                'practice_started_at' => null,
                'exotic_animals' => false,
                'On_site_assistance' => false,
                'photo' => null,
                'description' => 'Ветеринарный врач-терапевт, специализируется на общей терапии и ведении больных животных.',
            ],
        ];

        DB::table('doctors')->insert($doctors);
    }
}