<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Review;
use App\Models\Clinic;
use App\Models\Doctor;

class ReviewSeeder extends Seeder
{
    /**
     * Запуск сидера
     */
    public function run(): void
    {
        // Очищаем таблицу
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('reviews')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

$reviews = [
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2024-05-12',
        'rating' => 5,
        'content' => 'Отличная клиника, очень внимательное отношение к животным.',
        'liked' => 'Вежливый персонал, Квалифицированные врачи',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2024-06-01',
        'rating' => 4,
        'content' => 'Хорошие врачи, но пришлось подождать в очереди около 20 минут.',
        'liked' => 'Профессионализм',
        'disliked' => 'Очередь',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 1,
        'review_date' => '2024-06-15',
        'rating' => 5,
        'content' => 'Наталья Генриховна — врач от Бога! Спасла нашу кошку Ириску.',
        'liked' => 'Золотые руки, чуткость',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2024-07-10',
        'rating' => 3,
        'content' => 'Цены выше среднего, а ремонт в клинике староват.',
        'liked' => 'Чистота',
        'disliked' => 'Высокая стоимость',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2024-08-05',
        'rating' => 5,
        'content' => 'Очень современное оборудование, УЗИ сделали быстро.',
        'liked' => 'Новое оборудование',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 2,
        'review_date' => '2024-08-20',
        'rating' => 5,
        'content' => 'Дарья Борисовна провела сложную операцию, все прошло успешно.',
        'liked' => 'Хирургия высокого уровня',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 3,
        'review_date' => '2024-09-02',
        'rating' => 2,
        'content' => 'Администратор нахамил по телефону, записываться не стал.',
        'liked' => null,
        'disliked' => 'Сервис, хамство',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 3,
        'review_date' => '2024-09-12',
        'rating' => 5,
        'content' => 'Ангелина Михайловна очень подробно объяснила схему лечения.',
        'liked' => 'Терпеливость, знания',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2024-10-01',
        'rating' => 5,
        'content' => 'Лучшая клиника в городе, теперь только сюда.',
        'liked' => 'Все на высшем уровне',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 4,
        'review_date' => '2024-10-15',
        'rating' => 4,
        'content' => 'Удобная парковка, внутри уютно, есть аптека.',
        'liked' => 'Инфраструктура',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 4,
        'review_date' => '2024-11-03',
        'rating' => 5,
        'content' => 'Версения Сергеевна — замечательный анестезиолог, собака легко отошла от наркоза.',
        'liked' => 'Безопасность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2024-11-20',
        'rating' => 1,
        'content' => 'Поставили неверный диагноз, пришлось перелечиваться в другом месте.',
        'liked' => null,
        'disliked' => 'Низкая квалификация',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 5,
        'review_date' => '2024-12-05',
        'rating' => 5,
        'content' => 'Наталья Геннадьевна нашла подход даже к нашему очень трусливому псу.',
        'liked' => 'Психология животных',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 5,
        'review_date' => '2024-12-25',
        'rating' => 4,
        'content' => 'Хорошая клиника, но дозвониться бывает сложно.',
        'liked' => 'Врачи',
        'disliked' => 'Сложно дозвониться',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 6,
        'review_date' => '2025-01-10',
        'rating' => 5,
        'content' => 'Юлия Владимировна сделала отличный рентген и сразу всё прокомментировала.',
        'liked' => 'Оперативность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2025-01-22',
        'rating' => 5,
        'content' => 'Приятно, что в клинике всегда чисто и нет неприятных запахов.',
        'liked' => 'Гигиена',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 7,
        'review_date' => '2025-02-05',
        'rating' => 5,
        'content' => 'Вероника Александровна — отличный кардиолог, подобрала схему для сердца.',
        'liked' => 'Узкая специализация',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 3,
        'review_date' => '2025-02-18',
        'rating' => 4,
        'content' => 'Цены нормальные, помощь оказали быстро.',
        'liked' => 'Скорость',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 8,
        'review_date' => '2025-03-01',
        'rating' => 5,
        'content' => 'Батина Гажиевна помогла при родах, все щенки здоровы!',
        'liked' => 'Опыт, спокойствие',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 4,
        'review_date' => '2025-03-15',
        'rating' => 2,
        'content' => 'Очень долго ждали результаты анализов, обещали за день, в итоге три дня.',
        'liked' => null,
        'disliked' => 'Долгое ожидание анализов',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 9,
        'review_date' => '2025-03-20',
        'rating' => 5,
        'content' => 'Мишель Муфид — профессионал с большой буквы, сразу увидел проблему.',
        'liked' => 'Внимательность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2025-03-25',
        'rating' => 5,
        'content' => 'Работают круглосуточно, что очень выручило ночью.',
        'liked' => 'Круглосуточный режим',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 1,
        'review_date' => '2025-03-30',
        'rating' => 4,
        'content' => 'Врач хороший, но в клинике было очень шумно из-за ремонта.',
        'liked' => 'Лечение',
        'disliked' => 'Шум',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 5,
        'review_date' => '2025-04-01',
        'rating' => 5,
        'content' => 'Всегда вежливые администраторы, приятно приходить.',
        'liked' => 'Сервис',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 2,
        'review_date' => '2025-04-05',
        'rating' => 5,
        'content' => 'Спасибо за спасенного кота! Операция была сложная, но мы справились.',
        'liked' => 'Мастерство',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2025-04-07',
        'rating' => 3,
        'content' => 'Врачи отличные, но цены кусаются.',
        'liked' => 'Врачи',
        'disliked' => 'Цена',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 11,
        'review_date' => '2025-04-10',
        'rating' => 5,
        'content' => 'Гагик Артавазович провел эндоскопию без лишнего стресса для собаки.',
        'liked' => 'Бережное отношение',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 3,
        'review_date' => '2025-04-12',
        'rating' => 5,
        'content' => 'Очень быстро приняли с острой болью без очереди.',
        'liked' => 'Человечность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 12,
        'review_date' => '2025-04-14',
        'rating' => 4,
        'content' => 'Хороший хирург, шов зажил быстро.',
        'liked' => 'Качество работы',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 4,
        'review_date' => '2025-04-15',
        'rating' => 5,
        'content' => 'В клинике есть всё необходимое: от аптеки до стационара.',
        'liked' => 'Укомплектованность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 3,
        'review_date' => '2025-04-16',
        'rating' => 5,
        'content' => 'Офтальмолог просто супер, вылечили затяжной конъюнктивит.',
        'liked' => 'Знания',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2025-04-17',
        'rating' => 4,
        'content' => 'Чисто, аккуратно, врачи в масках и перчатках.',
        'liked' => 'Стерильность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 5,
        'review_date' => '2025-04-18',
        'rating' => 5,
        'content' => 'Терапевт очень грамотный, не назначает лишних анализов.',
        'liked' => 'Честность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2025-04-19',
        'rating' => 5,
        'content' => 'Нравится система напоминаний о прививках по СМС.',
        'liked' => 'Забота о клиентах',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 4,
        'review_date' => '2025-04-20',
        'rating' => 3,
        'content' => 'Врач опоздал на прием на 15 минут.',
        'liked' => 'Лечение',
        'disliked' => 'Непунктуальность',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 5,
        'review_date' => '2025-04-21',
        'rating' => 5,
        'content' => 'Есть отдельный вход для кошек, это очень снижает стресс.',
        'liked' => 'Продуманность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 8,
        'review_date' => '2025-04-22',
        'rating' => 5,
        'content' => 'Лучший узист, которого мы встречали.',
        'liked' => 'Точность диагностики',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2025-04-23',
        'rating' => 5,
        'content' => 'Помогли подобрать диетический корм для аллергика.',
        'liked' => 'Консультация по питанию',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 9,
        'review_date' => '2025-04-24',
        'rating' => 5,
        'content' => 'Невролог провел все тесты, назначил МРТ, сопровождал до конца.',
        'liked' => 'Профессионализм',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2025-04-25',
        'rating' => 4,
        'content' => 'Хорошо, но в коридоре тесновато, когда много собак.',
        'liked' => 'Врачи',
        'disliked' => 'Мало места',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 7,
        'review_date' => '2025-04-26',
        'rating' => 5,
        'content' => 'Врач очень спокойная, успокоила и нас, и собаку.',
        'liked' => 'Доброта',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 3,
        'review_date' => '2025-04-27',
        'rating' => 5,
        'content' => 'Цены соответствуют качеству услуг.',
        'liked' => 'Прозрачность расчетов',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 6,
        'review_date' => '2025-04-28',
        'rating' => 5,
        'content' => 'Рентген сделали без седации, врач умеет договариваться с животными.',
        'liked' => 'Подход к делу',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 4,
        'review_date' => '2025-04-29',
        'rating' => 4,
        'content' => 'Нормально, но долго искали нашу карту.',
        'liked' => 'Оборудование',
        'disliked' => 'Бюрократия',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 10,
        'review_date' => '2025-04-30',
        'rating' => 5,
        'content' => 'Ассистент очень бережно держал кота во время забора крови.',
        'liked' => 'Аккуратность',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 5,
        'review_date' => '2025-05-01',
        'rating' => 5,
        'content' => 'Всё чётко по записи, никакого ожидания.',
        'liked' => 'Тайм-менеджмент',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 1,
        'review_date' => '2025-05-02',
        'rating' => 5,
        'content' => 'Чувствуется огромный опыт и любовь к своему делу.',
        'liked' => 'Отношение',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 1,
        'review_date' => '2025-05-03',
        'rating' => 2,
        'content' => 'Слишком навязывают дополнительные услуги.',
        'liked' => 'Чистота',
        'disliked' => 'Маркетинг',
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Doctor::class,
        'reviewable_id' => 11,
        'review_date' => '2025-05-04',
        'rating' => 5,
        'content' => 'Удаляли инородное тело из желудка, спасли жизнь!',
        'liked' => 'Профессионализм',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
    [
        'user_id' => 1,
        'reviewable_type' => Clinic::class,
        'reviewable_id' => 2,
        'review_date' => '2025-05-05',
        'rating' => 5,
        'content' => 'Рекомендую всем знакомым, отличный сервис.',
        'liked' => 'Качество',
        'disliked' => null,
        'pet_id' => null,
        'receipt_path' => null,
    ],
];

        foreach ($reviews as $review) {
            Review::create([
                ...$review,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ Отзывы успешно добавлены.');
    }
}
