<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Запуск сидера
     */
    public function run(): void
    {
        // Очищаем таблицу
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('services')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $services = [
            // Терапевт
['name' => 'Первичный приём','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Повторный приём','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Общий осмотр животного','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Диагностика заболеваний','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Назначение лечения','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Составление плана лечения','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Интерпретация анализов','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Профилактический осмотр','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Вакцинация','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Дегельминтизация','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Обработка от паразитов','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Лечение инфекционных заболеваний','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Лечение хронических заболеваний','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Симптоматическое лечение','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Капельницы (инфузионная терапия)','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Инъекции','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Консультация по кормлению','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Консультация по уходу','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Онлайн-консультация','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],
['name' => 'Выезд на дом','specialization' => 'Терапия', 'specialization_doctor' => 'Терапевт'],

// Диагност
['name' => 'Консультация диагноста','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Комплексная диагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Сбор анамнеза','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Интерпретация анализов','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Лабораторная диагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'УЗИ диагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Рентген диагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'ЭКГ','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Эхокардиография','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Эндоскопия','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Биопсия','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Цитологические исследования','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Гистологические исследования','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Аллергодиагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Гормональные исследования','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Инфекционная диагностика','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Паразитологические исследования','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Контроль эффективности лечения','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Второе мнение по диагнозу','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
['name' => 'Онлайн-консультация','specialization' => 'Диагностика', 'specialization_doctor' => 'Диагност'],
// Хирург
['name' => 'Консультация хирурга','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Предоперационный осмотр','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Планирование операции','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Кастрация','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Стерилизация','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Удаление новообразований','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Абдоминальные операции','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Ортопедические операции','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Травматологические операции','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Удаление инородных тел','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Пластическая хирургия','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Стоматологические операции','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Операции на мягких тканях','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Операции на костях и суставах','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Наложение швов','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Обработка ран','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Послеоперационное наблюдение','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Снятие швов','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Экстренная хирургическая помощь','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],
['name' => 'Выезд на дом','specialization' => 'Хирургия', 'specialization_doctor' => 'Хирург'],

// Травматолог
['name' => 'Консультация травматолога','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Диагностика травм','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Лечение переломов','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Лечение вывихов','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Лечение растяжений','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Остеосинтез','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Иммобилизация конечностей','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Наложение гипса','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Реабилитация после травм','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Контроль заживления','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Лечение ран и ушибов','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Удаление инородных тел','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Обработка ран','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Перевязки','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Хирургическое лечение травм','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Ортопедическая коррекция','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Лечение заболеваний суставов','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Контроль после операций','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Экстренная помощь при травмах','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],
['name' => 'Онлайн-консультация','specialization' => 'Травматология', 'specialization_doctor' => 'Травматолог'],


// Гастроэнтеролог
['name' => 'Консультация гастроэнтеролога','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Диагностика заболеваний ЖКТ','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение гастрита','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение энтерита','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение колита','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение панкреатита','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение заболеваний печени','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение заболеваний желчного пузыря','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Интерпретация анализов','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'УЗИ органов брюшной полости','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Диетотерапия','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Подбор лечебного питания','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение рвоты','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Лечение диареи','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Эндоскопия ЖКТ','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Биопсия органов ЖКТ','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Контроль лечения','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Профилактика заболеваний ЖКТ','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Онлайн-консультация','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],
['name' => 'Второе мнение','specialization' => 'Гастроэнтерология', 'specialization_doctor' => 'Гастроэнтеролог'],

// Нефролог
['name' => 'Консультация нефролога','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Диагностика заболеваний почек','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Лечение хронической болезни почек','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Лечение острой почечной недостаточности','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Интерпретация анализов мочи','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Интерпретация биохимии крови','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'УЗИ почек','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Контроль артериального давления','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Диетотерапия при заболеваниях почек','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Подбор лечебного питания','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Лечение мочекаменной болезни','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Лечение инфекций мочевыводящих путей','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Катетеризация мочевого пузыря','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Контроль диуреза','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Инфузионная терапия','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Мониторинг состояния пациента','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Профилактика заболеваний почек','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Контроль эффективности лечения','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Онлайн-консультация','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],
['name' => 'Второе мнение','specialization' => 'Нефрология', 'specialization_doctor' => 'Нефролог'],

// Радиолог
['name' => 'Консультация радиолога','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Рентгенография','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Интерпретация рентген-снимков','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Компьютерная томография (КТ)','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Магнитно-резонансная томография (МРТ)','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Контрастные исследования','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'УЗИ диагностика','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Интерпретация КТ и МРТ','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Радиологическое заключение','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Диагностика опухолей','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Диагностика травм','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Диагностика заболеваний органов грудной клетки','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Диагностика заболеваний брюшной полости','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Оценка динамики лечения','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Второе мнение по снимкам','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Подготовка к исследованиям','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Контроль качества снимков','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Онлайн-интерпретация исследований','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Консультация по результатам исследований','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],
['name' => 'Архивация и хранение снимков','specialization' => 'Радиология', 'specialization_doctor' => 'Радиолог'],

// Офтальмолог
['name' => 'Осмотр глаз','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Диагностика зрения','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Лечение конъюнктивита','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Удаление инородных тел из глаза','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Проверка слезных каналов','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Лечение кератита','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Лечение глаукомы','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Лечение катаракты','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Операции на глазах','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Флюоресцеиновый тест','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Тонометрия','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Промывание глаз','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Назначение лечения','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Контроль лечения','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Лечение травм глаза','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Осмотр сетчатки','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Оценка зрения','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Подбор терапии','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Онлайн-консультация','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 
['name' => 'Второе мнение','specialization' => 'Офтальмология', 'specialization_doctor' => 'Офтальмолог'], 

// Анестезиолог
['name' => 'Подготовка к анестезии','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Подбор анестезии','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Общий наркоз','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Местная анестезия','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Седация','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Мониторинг пациента','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Контроль жизненных функций','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Пробуждение после наркоза','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Инфузионная поддержка','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Обезболивание','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Эпидуральная анестезия','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Анестезия при операциях','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Контроль дозировки препаратов','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Оценка рисков','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Послеоперационное обезболивание','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Интенсивное наблюдение','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Консультация перед операцией','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Контроль состояния','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Онлайн-консультация','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 
['name' => 'Второе мнение','specialization' => 'Анестезиология', 'specialization_doctor' => 'Анестезиолог'], 

// Иммунолог
['name' => 'Консультация иммунолога','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Оценка иммунного статуса','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Иммунологическая диагностика','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Интерпретация иммунограмм','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Лечение иммунодефицитов','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Лечение аутоиммунных заболеваний','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Иммунотерапия','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Подбор иммуномодуляторов','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Контроль иммунного ответа','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Диагностика аллергических реакций','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Профилактика инфекций','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Вакцинальный контроль','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Оценка поствакцинального иммунитета','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Коррекция иммунных нарушений','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Диагностика хронических инфекций','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Мониторинг лечения','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Подбор терапии','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Консультация по иммунопрофилактике','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Онлайн-консультация','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 
['name' => 'Второе мнение','specialization' => 'Иммунология', 'specialization_doctor' => 'Иммунолог'], 

// Аллерголог
['name' => 'Консультация аллерголога','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Диагностика аллергий','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Аллерготестирование','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Интерпретация анализов','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Лечение пищевой аллергии','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Лечение контактной аллергии','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Лечение атопии','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Подбор гипоаллергенной диеты','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Иммунотерапия аллергий','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Контроль лечения','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Диагностика кожных реакций','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Лечение зуда','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Лечение дерматитов','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Диагностика сезонных аллергий','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Профилактика аллергий','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Подбор терапии','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Мониторинг состояния','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Консультация по уходу','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Онлайн-консультация','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],
['name' => 'Второе мнение','specialization' => 'Аллергология', 'specialization_doctor' => 'Аллерголог'],

// Онколог
['name' => 'Консультация онколога','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Диагностика опухолей','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Онкоскрининг','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Интерпретация анализов','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Биопсия','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Цитологические исследования','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Гистологические исследования','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Стадирование опухоли','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Разработка плана лечения','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Химиотерапия','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Таргетная терапия','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Иммунотерапия','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Контроль лечения','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Мониторинг состояния','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Паллиативная помощь','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Обезболивание','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Поддерживающая терапия','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Консультация по уходу','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Онлайн-консультация','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],
['name' => 'Второе мнение','specialization' => 'Онкология', 'specialization_doctor' => 'Онколог'],

// Невролог
['name' => 'Консультация невролога','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Неврологический осмотр','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Диагностика неврологических заболеваний','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение судорог','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение эпилепсии','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение парезов и параличей','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Диагностика травм ЦНС','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Интерпретация МРТ и КТ','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение заболеваний позвоночника','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение невритов','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение невралгий','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Диагностика координационных нарушений','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Лечение тремора','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Контроль лечения','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Мониторинг состояния','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Подбор терапии','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Реабилитация после неврологических заболеваний','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Консультация по уходу','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Онлайн-консультация','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],
['name' => 'Второе мнение','specialization' => 'Неврология', 'specialization_doctor' => 'Невролог'],

// Дерматолог
['name' => 'Консультация дерматолога','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Осмотр кожи и шерсти','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Диагностика кожных заболеваний','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Соскоб кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Цитология кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение дерматитов','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение грибковых заболеваний','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение бактериальных инфекций кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение паразитарных заболеваний кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение зуда','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Диагностика аллергических кожных реакций','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Подбор лечебных шампуней','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Лечение алопеции','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Удаление новообразований кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Контроль лечения','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Мониторинг состояния кожи','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Подбор терапии','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Консультация по уходу за кожей','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Онлайн-консультация','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],
['name' => 'Второе мнение','specialization' => 'Дерматология', 'specialization_doctor' => 'Дерматолог'],

// Эндокринолог
['name' => 'Консультация эндокринолога','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Диагностика эндокринных заболеваний','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Интерпретация гормональных анализов','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Лечение сахарного диабета','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Контроль уровня глюкозы','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Лечение заболеваний щитовидной железы','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Диагностика гормональных нарушений','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Подбор гормональной терапии','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Лечение ожирения','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Диетотерапия при эндокринных заболеваниях','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Контроль лечения','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Мониторинг состояния','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Диагностика заболеваний надпочечников','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Лечение гормональных дисбалансов','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Подбор терапии','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Профилактика эндокринных заболеваний','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Консультация по кормлению','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Онлайн-консультация','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Второе мнение','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],
['name' => 'Долгосрочное наблюдение','specialization' => 'Эндокринология', 'specialization_doctor' => 'Эндокринолог'],


// Кардиолог
['name' => 'Консультация кардиолога','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Кардиологический осмотр','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Диагностика заболеваний сердца','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'ЭКГ','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Эхокардиография','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Холтер-мониторинг','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Измерение артериального давления','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Лечение сердечной недостаточности','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Лечение аритмий','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Лечение пороков сердца','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Интерпретация анализов','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Контроль лечения','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Мониторинг состояния','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Подбор терапии','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Профилактика заболеваний сердца','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Подготовка к операциям','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Послеоперационное наблюдение','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Консультация по нагрузкам','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Онлайн-консультация','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],
['name' => 'Второе мнение','specialization' => 'Кардиология', 'specialization_doctor' => 'Кардиолог'],

// Реабилитолог
['name' => 'Консультация реабилитолога','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Оценка функционального состояния','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Составление программы реабилитации','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Реабилитация после операций','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Реабилитация после травм','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Лечебная физкультура','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Массаж','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Физиотерапия','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Гидротерапия','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Кинезиотерапия','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Разработка суставов','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Восстановление подвижности','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Контроль восстановления','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Мониторинг состояния','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Подбор нагрузок','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Профилактика осложнений','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Реабилитация пожилых животных','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Консультация по уходу','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Онлайн-консультация','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],
['name' => 'Второе мнение','specialization' => 'Реабилитация', 'specialization_doctor' => 'Реабилитолог'],

// Реаниматолог
['name' => 'Консультация реаниматолога','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Интенсивная терапия','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Стабилизация состояния','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Мониторинг жизненных функций','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Кислородная терапия','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'ИВЛ','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Инфузионная терапия','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Реанимационные мероприятия','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Кардиореспираторная поддержка','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Лечение шоковых состояний','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Детоксикация','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Контроль состояния пациента','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Круглосуточное наблюдение','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Послеоперационная интенсивная терапия','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Поддержка при критических состояниях','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Коррекция электролитов','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Контроль дыхания','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Консультация по уходу','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Онлайн-консультация','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],
['name' => 'Второе мнение','specialization' => 'Реаниматология', 'specialization_doctor' => 'Реаниматолог'],

// Стоматолог
['name' => 'Консультация стоматолога','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Осмотр полости рта','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Профессиональная чистка зубов','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Удаление зубного камня','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Полировка зубов','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Лечение кариеса','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Удаление зубов','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Лечение гингивита','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Лечение стоматита','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Лечение пародонтита','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Рентген зубов','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Хирургическая стоматология','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Ортодонтические консультации','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Коррекция прикуса','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Лечение травм зубов','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Подбор ухода за зубами','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Контроль лечения','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Консультация по гигиене','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Онлайн-консультация','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],
['name' => 'Второе мнение','specialization' => 'Стоматология', 'specialization_doctor' => 'Стоматолог'],

// Ортопед
['name' => 'Консультация ортопеда','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Ортопедический осмотр','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Диагностика заболеваний опорно-двигательного аппарата','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Лечение дисплазии','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Лечение артрита','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Лечение артроза','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Диагностика хромоты','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Рентген суставов','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Лечение травм суставов','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Хирургия суставов','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Остеосинтез','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Иммобилизация конечностей','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Реабилитация после операций','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Контроль лечения','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Мониторинг состояния','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Подбор терапии','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Профилактика заболеваний суставов','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Консультация по нагрузкам','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Онлайн-консультация','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],
['name' => 'Второе мнение','specialization' => 'Ортопедия', 'specialization_doctor' => 'Ортопед'],

// Экзотолог
['name' => 'Консультация экзотолога','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Осмотр экзотических животных','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Диагностика заболеваний экзотических животных','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение рептилий','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение птиц','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение грызунов','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение амфибий','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение экзотических млекопитающих','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Диагностика паразитов','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Интерпретация анализов','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Подбор условий содержания','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Консультация по кормлению','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Профилактика заболеваний','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Лечение инфекционных заболеваний','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Контроль лечения','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Мониторинг состояния','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Подбор терапии','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Консультация по уходу','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Онлайн-консультация','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],
['name' => 'Второе мнение','specialization' => 'Экзотология', 'specialization_doctor' => 'Экзотолог'],

// Вет диетолог
['name' => 'Консультация диетолога','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Оценка рациона','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Составление рациона','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Подбор лечебного питания','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Диетотерапия при заболеваниях','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Коррекция веса','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Лечение ожирения','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Диета при аллергиях','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Диета при заболеваниях ЖКТ','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Диета при заболеваниях почек','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Диета при заболеваниях печени','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Подбор промышленного корма','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Натуральное питание','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Контроль питания','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Мониторинг состояния','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Подбор добавок','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Профилактическое питание','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Консультация по кормлению','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Онлайн-консультация','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],
['name' => 'Второе мнение','specialization' => 'Диетология', 'specialization_doctor' => 'Вет диетолог'],

    // Грумер
    ['name' => 'Гигиеническая стрижка','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Модельная стрижка','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Экспресс-линька','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Тримминг','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Стриппинг','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Купание и сушка','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Чистка ушей','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Стрижка когтей','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Чистка зубов','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Вычесывание колтунов','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Удаление колтунов','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'SPA-уход','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Озонотерапия шерсти','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Груминг кошек','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Груминг собак','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Подготовка к выставке','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Окрашивание шерсти','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Креативный груминг','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Полировка шерсти','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],
    ['name' => 'Парфюмирование','specialization' => 'Грумминг', 'specialization_doctor' => 'Грумер'],


    // Кинолог
    ['name' => 'Общий курс дрессировки (ОКД)','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Управляемая городская собака (УГС)','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Коррекция поведения','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Дрессировка щенков','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Индивидуальные занятия','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Групповые занятия','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Социализация собаки','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Обучение базовым командам','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Обучение послушанию','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Антиагрессия','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Работа со страхами','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Подготовка к выставкам','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Хендлинг','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Ноузворк (поиск запахов)','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Аджилити','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Защитно-караульная служба (ЗКС)','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Обучение охране территории','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Обучение поисково-спасательной службе','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Консультация кинолога','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],
    ['name' => 'Онлайн-дрессировка','specialization' => 'Кинология', 'specialization_doctor' => 'Кинолог'],


    // Тренер по аджилити
['name' => 'Введение в аджилити','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Базовая подготовка собаки к аджилити','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Обучение прохождению снарядов','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Тоннели и мягкие препятствия','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Барьеры и прыжковые элементы','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Слалом','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Контактные зоны (горка, бум, качели)','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Развитие скорости и координации','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Построение трасс','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Прохождение трасс разного уровня','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Подготовка к соревнованиям','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Разбор ошибок на трассе','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Индивидуальные тренировки','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Групповые тренировки','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Онлайн-консультации по аджилити','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Фитнес для собак (под аджилити)','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Развитие мотивации и драйва','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Обучение работе с хендлером','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Подготовка щенков к аджилити','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],
['name' => 'Реабилитационные тренировки после травм','specialization' => 'Аджилити', 'specialization_doctor' => 'Тренер по аджилити'],

    // Зоопсихолог
['name' => 'Консультация зоопсихолога','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Диагностика поведения животного','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Коррекция поведения','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Агрессия у животных','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Страхи и фобии','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Сепарационная тревога','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Деструктивное поведение','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Проблемы с туалетом','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Адаптация животного в новом доме','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Социализация животных','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Проблемы общения с другими животными','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Проблемы поведения у кошек','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Проблемы поведения у собак','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Подбор методов воспитания','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Подготовка к появлению нового питомца','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Помощь при смене условий содержания','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Работа с гиперактивностью','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Пищевое поведение','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Онлайн-консультация','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],
['name' => 'Составление плана коррекции','specialization' => 'Зоопсихология', 'specialization_doctor' => 'Зоопсихолог'],

    // Фелинолог
['name' => 'Консультация фелинолога','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Подбор породы кошки','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Оценка экстерьера кошки','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Подготовка к выставке','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Хендлинг кошек','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Консультация по уходу за кошкой','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Консультация по кормлению','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Разведение кошек','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Подбор пары для вязки','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Сопровождение беременности кошки','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Помощь при родах','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Оценка помёта','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Консультация по содержанию котят','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Социализация котят','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Проблемы поведения кошек','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Коррекция поведения кошек','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Подготовка документов для выставок','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Регистрация в фелинологических системах','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Онлайн-консультация','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],
['name' => 'Аудит питомника','specialization' => 'Фелинология', 'specialization_doctor' => 'Фелинолог'],

    // Заводчик
['name' => 'Консультация заводчика','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Продажа щенков','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Продажа котят','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Подбор питомца','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Подбор пары для вязки','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Организация вязки','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Сопровождение беременности','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Помощь при родах','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Выращивание помёта','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Социализация щенков и котят','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Первичная вакцинация','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Чипирование','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Оформление документов на питомца','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Консультация по уходу','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Консультация по кормлению','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Передержка животных','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Подготовка к выставке','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Оценка экстерьера','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Консультация после покупки','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],
['name' => 'Резервирование питомца','specialization' => 'Разведение животных', 'specialization_doctor' => 'Заводчик'],

    // Зооняня
['name' => 'Выгул животных','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Кормление животных','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Уход за питомцем на дому','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Передержка животных','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Дневная няня для питомца','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Ночная передержка','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Посещение питомца на дому','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Уборка лотка/клетки','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Игры и активность','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Присмотр за питомцем во время отпуска','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Уход за пожилыми животными','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Уход за щенками и котятами','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Доставка питомца (зоотакси)','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Сопровождение к ветеринару','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Приём лекарств питомцем','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Фото- и видеоотчёт','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Онлайн-наблюдение за питомцем','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Экстренный выезд','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Уход за экзотическими животными','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
['name' => 'Консультация по уходу','specialization' => 'Зооняня', 'specialization_doctor' => 'Зооняня'],
       

// Зооцентр

        ['name' => 'Консультация специалиста','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Первичный приём','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Комплексный осмотр','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Вакцинация','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Чипирование','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Груминг услуги','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Стрижка животных','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Купание и уход','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Передержка животных','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Гостиница для животных','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Дрессировка','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Консультация кинолога','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Продажа товаров для животных','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Подбор кормов','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Диагностика заболеваний','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Лабораторные анализы','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Выезд на дом','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Онлайн-консультация','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Консультация по уходу','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],
['name' => 'Комплексные услуги','specialization' => 'Зооцентр', 'specialization_doctor' => 'Зооцентр'],

// Груминг салон
['name' => 'Консультация грумера','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Гигиеническая стрижка','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Модельная стрижка','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Купание и сушка','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Экспресс-линька','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Вычесывание шерсти','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Удаление колтунов','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Стрижка когтей','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Чистка ушей','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Чистка зубов','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'SPA-уход','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Озонотерапия шерсти','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Окрашивание шерсти','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Креативный груминг','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Полировка шерсти','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Парфюмирование','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Груминг кошек','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Груминг собак','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Подготовка к выставке','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],
['name' => 'Онлайн-консультация','specialization' => 'Груминг салон', 'specialization_doctor' => 'Груминг салон'],

// Кинологический центр
['name' => 'Консультация кинолога','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Диагностика поведения','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Базовая дрессировка','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Общий курс послушания','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Коррекция поведения','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Социализация собак','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Работа с агрессией','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Обучение щенков','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Подготовка к выставкам','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Подготовка к соревнованиям','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Индивидуальные тренировки','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Групповые занятия','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Дрессировка на площадке','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Выездные занятия','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Обучение командам','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Подготовка служебных собак','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Тестирование поведения','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Консультация по содержанию','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Онлайн-консультация','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],
['name' => 'Второе мнение','specialization' => 'Кинологический центр', 'specialization_doctor' => 'Кинологический центр'],

// Фелинологический клуб
['name' => 'Консультация по животным','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Подбор породы животного','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Оценка породных качеств','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Оформление родословной','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Регистрация помёта','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Актировка молодняка','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Подготовка животных к выставке','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Организация выставок животных','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Судейство на выставках','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Выдача титулов и сертификатов','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Консультация по разведению','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Подбор пары для вязки','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Контроль вязки','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Оценка генетических рисков','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Консультация по уходу','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Консультация по кормлению','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Обучение заводчиков','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Проверка стандартов пород','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Регистрация питомников','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],
['name' => 'Выдача племенных документов','specialization' => 'Фелинологический клуб','specialization_doctor' => 'Фелинологический клуб'],

// Питомник
['name' => 'Продажа животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Резервирование животного','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Консультация по выбору животного','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Передача животного новым владельцам','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Оформление ветеринарного паспорта','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Вакцинация животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Чипирование животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Стерилизация и кастрация','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Подбор пары для разведения','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Организация вязки','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Выращивание и социализация животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Консультация по уходу','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Консультация по кормлению','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Подготовка к выставкам','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Передержка животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Груминг животных','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Продажа кормов и аксессуаров','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Помощь в транспортировке','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Оформление документов на вывоз','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],
['name' => 'Поддержка владельцев','specialization' => 'Питомник','specialization_doctor' => 'Питомник'],

// Зоогостиница
['name' => 'Передержка животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Краткосрочное размещение','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Долгосрочное размещение','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Индивидуальный уход за животными','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Кормление по графику','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Специальное диетическое кормление','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Выгул животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Уборка и гигиена','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Медикаментозный уход','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Наблюдение за состоянием здоровья','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Груминг животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Игры и социализация','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Отдельные номера для животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'VIP-размещение','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Видеонаблюдение для владельцев','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Фото- и видеоотчёты','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Транспортировка животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Приём экзотических животных','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Уход за пожилыми животными','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],
['name' => 'Консультация владельцев','specialization' => 'Зоогостиница','specialization_doctor' => 'Зоогостиница'],

 ];
foreach ($services as $service) {
    DB::table('services')->insert([
        ...$service,
        'created_at' => now(),
        'updated_at' => now(),
    ]);
}
        $this->command->info('✅ Услуги успешно добавлены.');
    }
}
