<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Organization;

class VetapSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organizations = [
    [
        'name' => 'ВетАптека №1 на проспекте Острякова',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'проспект Острякова',
        'house' => '9',
        'address_comment' => 'розничный магазин, отдел оптовой торговли, отдел закупок',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 09.00 - 21.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Металлургическая',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Металлургическая',
        'house' => '1',
        'address_comment' => '',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Пт 10.00 - 20.00',
        'workdays' => 'Пн–Пт',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Алеутская',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Алеутская',
        'house' => '41',
        'address_comment' => '',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 20.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Сахалинская',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Сахалинская',
        'house' => '41г',
        'address_comment' => 'ТЦ "Орион" первый этаж',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 20.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Лермонтова',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Трудовое',
        'street' => 'ул. Лермонтова',
        'house' => '77Б',
        'address_comment' => 'ТЦ «Андромеда» второй этаж',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 20.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Мичуринская',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Мичуринская',
        'house' => '2',
        'address_comment' => '',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 21.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Крыгина',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Крыгина',
        'house' => '23',
        'address_comment' => '',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 21.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на пр-кт 100 лет Владивостоку',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'пр-кт 100 лет Владивостоку',
        'house' => '40',
        'address_comment' => 'ТЦ Сотка',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 10.00 - 21.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
    [
        'name' => 'ВетАптека №1 на ул. Семёновская',
        'field_of_activity_id' => 33,
        'country' => 'Россия',
        'region' => 'Приморский край',
        'city' => 'Владивосток',
        'street' => 'ул. Семёновская',
        'house' => '25',
        'address_comment' => '',
        'logo' => null,
        'description' => ' ',
        'phone1' => '8(423)202-51-15',
        'phone2' => '+7(914)703-76-43',
        'email' => null,
        'telegram' => null,
        'whatsapp' => null,
        'website' => 'https://vetaptekadv.ru/',
        'schedule' => 'Пн — Вс 09.00 - 21.00',
        'workdays' => 'Пн–Вс',
        'seo_title' => null,
        'seo_description' => null,
    ],
        ];

        
foreach ($organizations as $org) {
    // Используем updateOrCreate или create, чтобы сработали Observer/Boot события модели
    Organization::create([
        'name'               => $org['name'],
        'field_of_activity_id' => $org['field_of_activity_id'] ?? null,
        'country'            => $org['country'] ?? 'Россия',
        'region'             => $org['region'] ?? null,
        'city'               => $org['city'],
        'street'             => $org['street'],
        'house'              => $org['house'],
        'logo'              => $org['logo'],
        'description' => ' ',
        'website'             => $org['website'] ?? null,
        'phone1'             => $org['phone1'] ?? null,
        'schedule'             => $org['schedule'],
        'workdays'             => $org['workdays'] ?? null,
        'email'              => $org['email'] ?? null,
    ]);
}
    }
}